# -*- mode: ruby -*-
# vi: set ft=ruby :

NUM_VMS = 3
SUBNET = "192.168.30"
BASE_HOST = 41
HOSTNAME = "spark"
SSH_KEY = "~/.ssh/id_rsa"

VAGRANT_API_VERSION = "2"

(1..NUM_VMS).each do |i|
  Vagrant.configure(VAGRANT_API_VERSION) do |config|
      config.vm.define "#{HOSTNAME}-#{i}" do |pb|
          #######################
          # machine configuration
          #######################
          pb.vm.box = "boxcutter/ubuntu1404"

          ########################
          # Provider configuration
          ########################
          # virtualbox
          pb.vm.provider :virtualbox do |vb, override|
              vb.memory = 1024 * 2
              override.vm.hostname = "#{HOSTNAME}-#{i}"
              override.vm.network "private_network",
                ip: "#{SUBNET}.#{BASE_HOST + i - 1}"
          end

          ###############
          # Synced folder
          ###############
          # if not set to rsync, /etc/exports gets overwritten with each
          # - machine and causes a stale file handle error on all but
          # - the last machine configured
          pb.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: false

          ###########
          # Provision
          ###########
          # ssh settings
          config.ssh.insert_key = false
          config.ssh.private_key_path = ["#{SSH_KEY}", "~/.vagrant.d/insecure_private_key"]
          config.vm.provision "file", source: "#{SSH_KEY}", destination: "~/.ssh/#{SSH_KEY.split('/')[-1]}"
          config.vm.provision "file", source: "#{SSH_KEY}.pub", destination: "~/.ssh/authorized_keys"
          config.vm.provision "shell", path: "bin/setup.sh"
      end
  end
end
