export PATH="{{ ANACONDA_INSTALL }}/anaconda/bin:{{ SPARK_INSTALL }}/bin:{{ HDFS_INSTALL }}/bin:{{ HDFS_INSTALL }}/sbin:$PATH"
export HADOOP_COMMON_LIB_NATIVE_DIR="{{ HDFS_INSTALL }}/lib/native"
export HADOOP_OPTS="-Djava.library.path={{ HDFS_INSTALL }}/lib"
export HADOOP_HOME="{{ HDFS_INSTALL }}"
export HADOOP_COMMON_HOME="{{ HDFS_INSTALL }}"
export HADOOP_CONF_DIR="{{ HDFS_INSTALL }}/etc/hadoop"
export HADOOP_HDFS_HOME="{{ HDFS_INSTALL }}"
export HADOOP_MAPRED_HOME="{{ HDFS_INSTALL }}"
export HADOOP_YARN_HOME="{{ HDFS_INSTALL }}"
export PYSPARK_PYTHON="{{ ANACONDA_INSTALL }}/anaconda/bin/python"
export PYSPARK_DRIVER_PYTHON="{{ ANACONDA_INSTALL }}/anaconda/bin/ipython"
export PYSPARK_DRIVER_PYTHON_OPTS="notebook --no-browser --port=7777"
